# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Featured Projects
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/ZanattaMichael
      - name: LinkedIn
        icon: linkedin-square
        link: https://www.linkedin.com/in/michael-zanatta-61670258
      - name: Twitter
        icon: twitter
        link: https://twitter.com/PowerShellMich1
      - name: Twitch
        icon: twitch
        link: https://www.twitch.tv/PowerShellMichael
      - name: Brisbane PowerShell User Group
        icon: youtube
        link: https://www.youtube.com/channel/UCQfLvFYohCCm_gTPEUfaAbw
      - name: Brisbane PowerShell User Group Meetup
        icon: meetup
        link: https://www.meetup.com/Brisbane-PowerShell-User-Group